# Joining tables in Numpy
This notebook uses a simple use case to understand and practice NumPy methods (concatenate, vstack and hstack) for joining tables.

## Store information in np arrays
Let's say that we work for a sports academy that trains young athletes. Two of academy's athletes are 100m runners.
We have used a numpy array to store the numbers that represent the performance of each athlete in seconds for the last four races they have participated in.

In [1]:
import numpy as np

In [2]:
# create two arrays to store the performance (in sec) of the two athletes on 4 races of 100m running 
athlete1 = np.array([13.00, 12.55, 12.35, 11.55])
athlete2 = np.array([12.40, 12.35, 12.30, 12.05])

## Stack np arrays

Next, we want to create a table (matrix) to store the information about both athletes' performance. 
- In the first table that we want to make, we want each row to represent a different athlete.
- In the second table that we want to make, we want each row to represent a different race.

In [3]:
# combine athlete1 and athlete2 arrays using vertical stacking
athletes_matrix = np.vstack((athlete1, athlete2))
print(athletes_matrix)

[[13.   12.55 12.35 11.55]
 [12.4  12.35 12.3  12.05]]


In [4]:
# combine athlete1 and athlete2 arrays using column-wise stacking
races_matrix = np.c_[athlete1, athlete2]
print("Using column-wise stacking")
print(races_matrix)

# combine athlete1 and athlete2 arrays using horizontal stacking
athlete1_trans = athlete1.reshape(-1,1)
athlete2_trans = athlete2.reshape(-1,1)
races_matrix1 = np.hstack((athlete1_trans, athlete2_trans))
print("Using transpose and horizontal stacking")
print(races_matrix1)

Using column-wise stacking
[[13.   12.4 ]
 [12.55 12.35]
 [12.35 12.3 ]
 [11.55 12.05]]
Using transpose and horizontal stacking
[[13.   12.4 ]
 [12.55 12.35]
 [12.35 12.3 ]
 [11.55 12.05]]


We used stacking to combine athlete1 and athlete2 into athletes_matrix and races_matrix. In athletes_matrix each row represents an athlete (and as a consequence each column represents a race). In races_matrix each row represents a race (and as a consequence each column represents an athlete). 

In both cases, we used two 1d-arrays to create one 2d-array. Vertical stacking helped us placing the arrays the one under the other and horizontal stacking helped us placing the arrays the one next to the other. Note that stacking have combined the arrays by adding one more dimension to the new array.

## Concatenate np arrays

For another project, we create two arrays to store the performance of one athlete during two different seasons (4 races in each season).

In [5]:
# create another two arrays to store the performance of one athlete during two different sport seasons
season1 = np.array([13.00, 12.45, 12.35, 11.50])
season2 = np.array([12.50, 12.35, 12.10, 12.05])

It is very possible we need to analyze the overall progress of the athlete. For that, we need at first to store the information of both seasons in one array.

In [7]:
# combine season1 and season2 arrays using concatenation
two_years_performance = np.concatenate((season1, season2))
print(two_years_performance)

[13.   12.45 12.35 11.5  12.5  12.35 12.1  12.05]


We used concatenation to create two_years_performance matrix. Concatetation has helped us combine the two arrays without adding a new dimension to the new array. In simple words, the first array seems to be appended with the content of the second array. The two arrays before concatenation are 1-dimensional, so it is the new array after concatenation.

## Add new athletes

In [ ]:
# lets imagine that there two more athletes added in our training team and we want to include their performances in the matrices we have created
new_athletes = np.array([[12.4, 12.45, 13.10, 12.30], [12.5, 13.00, 12.20, 12.15]])
print("new athletes", new_athletes)

new athletes [[12.4  12.45 13.1  12.3 ]
 [12.5  13.   12.2  12.15]]


In [ ]:
# to add new athletes to the athletes matrix, we need to use concatetation 
athletes_matrix_new = np.concatenate((athletes_matrix, new_athletes), axis=0)
print(athletes_matrix_new)

[[13.   12.55 12.35 11.55]
 [12.4  12.35 12.3  12.05]
 [12.4  12.45 13.1  12.3 ]
 [12.5  13.   12.2  12.15]]


In [ ]:
# to add new athletes to the races matrix, we need to use horizontal stacking (or column-wise stacking)

# turn rows into columns in new_athletes
new_athletes_races = new_athletes.T
# column-wise stacking
races_matrix_new = np.hstack((races_matrix, new_athletes_races))
print(races_matrix_new)

[[13.   12.4  12.4  12.5 ]
 [12.55 12.35 12.45 13.  ]
 [12.35 12.3  13.1  12.2 ]
 [11.55 12.05 12.3  12.15]]


In [ ]:
# test vertical stacking (it matches how concatenation woyld have worked)
races_matrix_new = np.vstack((races_matrix, new_athletes_races))
print(races_matrix_new)

[[13.   12.4 ]
 [12.55 12.35]
 [12.35 12.3 ]
 [11.55 12.05]
 [12.4  12.5 ]
 [12.45 13.  ]
 [13.1  12.2 ]
 [12.3  12.15]]
